# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: React by vite

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/front-app.yml"
      - "front-app/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/front-app.yml"
      - "front-app/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Assume role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ap-northeast-1
        role-to-assume: ${{ secrets.ASSUME_ROLE_ARN_CICD }}
        role-session-name: "github-actions-memo-app"

    - name: npm build and upload
      run: |
        cd ./front-app
        npm install
        npm run build
        aws s3 sync dist/ s3://memo-app-bucket-react-exercise3
